# Generated by Django 3.1.5 on 2021-03-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('date', models.DateField()),
                ('discription', models.TextField()),
                ('amount', models.IntegerField()),
                ('payment_party', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.book')),
            ],
        ),
    ]
